### ISSUE TITLE
Serverless Membership Infrastructure

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/graphql-lambda#8]
We need the backend for Membership configured in AWS. We are using a serverless [Infrastructure as Code](https://serverless-stack.com/chapters/what-is-infrastructure-as-code.html) approach. This task includes designing the deployment of AWS membership infrastructure.

### Requirements
* [ ] Members can create new accounts with AWS
* [ ] Memberships can be authorized using Email, Password Approach
* [ ] Admin ability to retrieve a list of all users
* [ ] Admin ability to access individual user details

### Membership Fields (* indicates required)

* email * 
* first and last name *
* Date of Birth
* Full Address
* Phone Number
* T-Shirt Size

### Tasks
* [ ] Configure AWS Cognito User Pools YAML
* [ ] Configure AWS Cognito Identity Pools YAML
* [ ] If needed... configure DynamoDB Collection YAML for additional user info?
* [ ] Test serverless deployment, make sure it works locally 

related to HighFivesFoundation/schema-provider#19
related to HighFivesFoundation/website#82
