### ISSUE TITLE
Membership API

### ISSUE THREAD

**Issue by MoonTahoe** [HighFivesFoundation/graphql-lambda#9]
With the Infrastructure from #8  in place, we are ready to create the Membership API. This is where we link the AWS backend cognito membership resources to the GraphQL Schema so that clients can create new user accounts and login.

### Requirements
* [ ] members can create new base accounts with GraphQL
* [ ] members can login with GraphQL and recieve JWT token
* [ ] members can be listed and found using GraphQL

### Tasks
* [ ] Apply Necessary Tweaks to [schema](https://github.com/HighFivesFoundation/schema-provider/issues)
* [ ] Create Membership accounts with `createAccount` mutation
* [ ] Authorize members with `authorize` mutation
* [ ] `allMembers` Query
* [ ] Find individual `Member` Query
* [ ] Provide a logout mutation to sign user out of AWS

related to HighFivesFoundation/schema-provider#19
related to HighFivesFoundation/website#82
